In [1]:
import torch

In [2]:
import torchvision

In [3]:
print(torch.cuda.is_available())

False


### PyTorch Tensors

In [4]:
# 1-D tensor
a = torch.tensor([1,2,3,4,5])
print(a)

tensor([1, 2, 3, 4, 5])


In [6]:
# 2-D tensor
b = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(b)

tensor([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])


In [7]:
# The size of tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([5])
torch.Size([4, 3])
torch.Size([5])
torch.Size([4, 3])


In [8]:
# Get the height/number of rows of b
print(b.shape[0])

4


In [9]:
# Creating a float tensor
c = torch.FloatTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])

In [10]:
d = torch.DoubleTensor([[2,1,4],[3,5,4],[1,2,0],[4,3,2]])

In [11]:
print(c)
print(c.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [12]:
print(d)
print(d.dtype)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [13]:
print(c.mean())

tensor(2.5833)


In [14]:
print(d.mean())

tensor(2.5833, dtype=torch.float64)


In [15]:
# Reshaping Dimensions
# Note if one of the dimensions is -1, its size can be inferred
print(b.view(-1,1))
print(b.view(12))
print(b.view(-1,4))
print(b.view(3,4))

# Assign b a new shape
b = b.view(1,-1)
print(b)
print(b.shape)

# Reshaping 3-D Tensors
print('\n')
# Create a 3-D Tensor with 2 channels, 3 rows and 4 columns (channels, rows, columns)
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2,12)) # reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12]])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])
tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])
torch.Size([1, 12])




tensor([[[ 0.3190, -1.2009, -0.8806,  0.3444],
         [-0.3331, -2.2965,  0.6967,  0.8204],
         [ 0.5752,  1.2003,  0.3377, -0.8904]],

        [[-0.3442, -0.2970,  1.0511, -0.6119],
         [-0.4607, -0.9849, -0.2095, -0.9990],
         [-1.0417, -1.5232, -0.4276,  0.7627]]])
tensor([[ 0.3190, -1.2009, -0.8806,  0.3444, -0.3331, -2.2965,  0.6967,  0.8204,
          0.5752,  1.2003,  0.3377, -0.8904],
        [-0.3442, -0.2970,  1.0511, -0.6119, -0.4607, -0.9849, -0.2095, -0.9990,
         -1.0417, -1.5232, -0.4276,  0.

In [16]:
# Create a matrix with random numbers between 0 and 1
r = torch.rand(4,4)
print(r)

tensor([[0.2759, 0.6062, 0.1990, 0.3906],
        [0.3990, 0.5670, 0.9401, 0.8140],
        [0.1454, 0.6815, 0.4137, 0.7495],
        [0.3258, 0.8657, 0.9298, 0.6131]])


In [17]:
# create a matrix wth random numbers taken from a normal dstribution with mean 0 and variance 1
r2 = torch.randn(4,4)
print(r2)
print(r2.dtype)

tensor([[ 0.3786, -0.1303, -0.5101, -0.1229],
        [-0.2366,  0.0209, -0.4130, -1.8125],
        [ 0.4050,  1.4069, -0.7185,  1.0751],
        [-0.0021, -0.7168, -0.6318, -0.8820]])
torch.float32


In [19]:
# create an array of 5 random integers from values between 6 and 9(exlusive of 10)
in_array = torch.randint(6,10,(5,))
print(in_array)
print(in_array.dtype)

tensor([8, 6, 7, 9, 9])
torch.int64


In [20]:
# create a 2-D array (or matrix) of size 3x3 random integers from values between 6 and 9(exlusive of 10)
in_array2 = torch.randint(6,10,(3,3))
print(in_array2)
print(in_array2.dtype)

tensor([[9, 6, 8],
        [8, 9, 9],
        [7, 6, 8]])
torch.int64


In [22]:
# Get the number of elements in an array
print(torch.numel(in_array))
print(torch.numel(in_array2))

5
9


In [24]:
# Construct a 3x3 matrix of zeros and of dtype long
z = torch.zeros(3,3, dtype=torch.long)
print(z)

# construct a 3x3 matrix of ones
o = torch.ones(3,3)
print(o)
print(o.dtype)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [25]:
# convert the data type of the tensors
r2_like = torch.randn_like(r2, dtype=torch.double)
print(r2_like)

tensor([[-1.6278, -1.1468, -0.4879, -0.0584],
        [ 0.7172, -0.4084,  2.7190,  0.7063],
        [ 0.2640,  0.7372,  0.4155, -0.9387],
        [-1.4283, -0.3509,  1.2146,  1.4657]], dtype=torch.float64)


In [26]:
# Add two tensors, make sure they are the same size and data type
add_result = torch.add(r, r2)
print(add_result)

tensor([[ 0.6544,  0.4758, -0.3110,  0.2677],
        [ 0.1624,  0.5878,  0.5270, -0.9985],
        [ 0.5504,  2.0884, -0.3048,  1.8246],
        [ 0.3237,  0.1489,  0.2980, -0.2689]])


In [27]:
# I-place addition (change the value of r2)
r2.add_(r) # you do not need to do r2 = torch.add(r,r2)
print(r2)

tensor([[ 0.6544,  0.4758, -0.3110,  0.2677],
        [ 0.1624,  0.5878,  0.5270, -0.9985],
        [ 0.5504,  2.0884, -0.3048,  1.8246],
        [ 0.3237,  0.1489,  0.2980, -0.2689]])


In [28]:
# matrix slicing 
print(r2[:,1])
print(r2[:,:2])
print(r2[:3,:])
num_ten = r2[2,3]
print(num_ten)
print(num_ten.item())
print(r2[2,:])

tensor([0.4758, 0.5878, 2.0884, 0.1489])
tensor([[0.6544, 0.4758],
        [0.1624, 0.5878],
        [0.5504, 2.0884],
        [0.3237, 0.1489]])
tensor([[ 0.6544,  0.4758, -0.3110,  0.2677],
        [ 0.1624,  0.5878,  0.5270, -0.9985],
        [ 0.5504,  2.0884, -0.3048,  1.8246]])
tensor(1.8246)
1.8246291875839233
tensor([ 0.5504,  2.0884, -0.3048,  1.8246])
